### PR TITLE
Update autosmp.c

### PR DESCRIPTION
**Pull request by Keridos**
Trying to fix autosmp. Needs to be checked though.
See #6
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/ryan-andri/android_kernel_santoni/pull/7%23issuecomment-378069878%22%2C%20%22https%3A//github.com/ryan-andri/android_kernel_santoni/pull/7%23issuecomment-378072746%22%2C%20%22https%3A//github.com/ryan-andri/android_kernel_santoni/pull/7%23issuecomment-378077768%22%2C%20%22https%3A//github.com/ryan-andri/android_kernel_santoni/pull/7%23issuecomment-378084283%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/ryan-andri/android_kernel_santoni/pull/7%23issuecomment-378069878%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Thanks%20for%20trying%20to%20help%2C%20i%20really%20appreciate%20that.%5Cr%5Cnbut%20%2A%2Anr_cpu_online_lc%2A%2A%20or%20%2A%2Anr_cpu_online_bc%2A%2A%20is%20only%20variable%20which%20it%20only%20to%20check%20how%20many%20cores%20online.%5Cr%5Cnthe%20variable%20%2A%2Anr_cpu_online_lc/nr_cpu_online_bc%20%2B%3D%201%2A%2A%20is%20filled%20by%201%20because%20the%20cpu%200%20and%20cpu%204%20never%20offlined%20that%20should%20be%201%20online%20in%20case%20looping%20cpu%20online%20is%20passed%20with%20zero%20value.%22%2C%20%22created_at%22%3A%20%222018-04-02T22%3A44%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/4983926%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ryan-andri%22%7D%7D%2C%20%7B%22body%22%3A%20%22Well%20you%20do%20not%20set%20it%20to%201%20you%20add%201%20to%20it%2C%20you%20should%20just%20use%20%3D%20instead%20of%20%2B%3D%20then%22%2C%20%22created_at%22%3A%20%222018-04-02T22%3A59%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/2742845%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Keridos%22%7D%7D%2C%20%7B%22body%22%3A%20%22yes%2C%20i%20set%20it%20to%20%2B%3D%201%20which%20mean%20is%20%2B1.%5Cr%5Cnso%20any%20values%20after%20cpu%20online%20looping%20%28for_each_online_cpu%29%20will%20added%20with%20%2B1.%5Cr%5Cnif%20i%20set%20to%20%3D%201%20and%20the%20nr_cpu_online_bc/lc%20will%20always%20contain%201%2C%20you%20can%20check%20it%20again%20%3B%29%22%2C%20%22created_at%22%3A%20%222018-04-02T23%3A14%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars0.githubusercontent.com/u/4983926%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ryan-andri%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yeah%20now%20I%20see%20it.%20I%20might%20add%20some%20more%20comments%20to%20clarify%20a%20few%20more%20things%20once%20I%20get%20my%20build%20env%20going.%22%2C%20%22created_at%22%3A%20%222018-04-02T23%3A54%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/2742845%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Keridos%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/ryan-andri/android_kernel_santoni/pull/7#issuecomment-378069878'>General Comment</a></b>
- <a href='https://github.com/ryan-andri'></a> Thanks for trying to help, i really appreciate that.
but **nr_cpu_online_lc** or **nr_cpu_online_bc** is only variable which it only to check how many cores online.
the variable **nr_cpu_online_lc/nr_cpu_online_bc += 1** is filled by 1 because the cpu 0 and cpu 4 never offlined that should be 1 online in case looping cpu online is passed with zero value.
- <a href='https://github.com/Keridos'></a> Well you do not set it to 1 you add 1 to it, you should just use = instead of += then
- <a href='https://github.com/ryan-andri'></a> yes, i set it to += 1 which mean is +1.
so any values after cpu online looping (for_each_online_cpu) will added with +1.
if i set to = 1 and the nr_cpu_online_bc/lc will always contain 1, you can check it again ;)
- <a href='https://github.com/Keridos'></a> Yeah now I see it. I might add some more comments to clarify a few more things once I get my build env going.

<a href='https://www.codereviewhub.com/ryan-andri/android_kernel_santoni/pull/7?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/ryan-andri/android_kernel_santoni/pull/7?approve=1'></a>&nbsp;<a href='https://github.com/ryan-andri/android_kernel_santoni/pull/7'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by ryan-andri** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/ryan-andri/android_kernel_santoni/pull/7'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by ryan-andri** [comment]
Thanks for trying to help, i really appreciate that.
but **nr_cpu_online_lc** or **nr_cpu_online_bc** is only variable which it only to check how many cores online.
the variable **nr_cpu_online_lc/nr_cpu_online_bc += 1** is filled by 1 because the cpu 0 and cpu 4 never offlined that should be 1 online in case looping cpu online is passed with zero value.

**Comment by Keridos** [comment]
Well you do not set it to 1 you add 1 to it, you should just use = instead of += then

**Comment by ryan-andri** [comment]
yes, i set it to += 1 which mean is +1.
so any values after cpu online looping (for_each_online_cpu) will added with +1.
if i set to = 1 and the nr_cpu_online_bc/lc will always contain 1, you can check it again ;)

**Comment by Keridos** [comment]
Yeah now I see it. I might add some more comments to clarify a few more things once I get my build env going.

**Pull request closed without merging**
